language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: cGe6iUv6bywUoTiYorNlPorIm9W3+RZ+jQkAn+Ib81pNQHkA2Rn3wHHScF220/ivMcXJtVKWau+CKrzxW+A5ogPYC2+b0+V9yu3AskWEMxwFkLDdUiwdtfQuHuWbZltE/CpmNW/CMCpqaSNIEUmsvP8mjsnZU/TxcPKy71Yka/LWNrSzsX7Sz0Q2hxz17zLHolcl9Ycevq1YkTU+Y+P2Iogk+eN21kppCt0fNLT6l78PsnAe3MPkCXmGy3mJM91yJXuli3E20AH+02jDAdJDoX/SNg4ObaqCTwAZ4tL/5AwhgTcSrHUl1Q5FfiK6OTu/I2btRK4ezItnnlj9hoCWOrPncRX/9hmHg6DRUL6Qk9t6hMIDtcuhlSSnLqiioqNGeq5u0n8FG7NaKg++nZfGpio4sEgD6wsaLH9rYiumBGJD6OVdVChvts+yzfse4kOmSVr80QQLawMdJ+WNoMyUyLfhQC3Mu+o1NVo6htGDZufUXe49r8kcLuqvNQDpzOgrMbmgiG0lOxp+0icSChG7RWmhqVfEAOGiKj9SK/Tef0lJ4aSv7+gmI1WBvWvNeH0vYK0PaKc3Ru8SJ3TlXHJVoMIUmeEgtPVAc5COmFblrxT9juKVQqSbociIGF2pC/PwFpPOSlrLam3Jg8/Zw7o+vj9Rxb8yqlJWXJFY6dzhgfo=
  on:
    branch: master
    tags: true
    repo: deg-skeletor/skeletor-core
